/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SORT_H_RPCGEN
#define _SORT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSORTSIZE 64
#define MAXSTRINGLEN 64

typedef char *str;

struct sortstrings {
	struct {
		u_int ss_len;
		str *ss_val;
	} ss;
};
typedef struct sortstrings sortstrings;

#define SORTPROG 22855
#define SORTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SORT 1
extern  sortstrings * sort_1(sortstrings *, CLIENT *);
extern  sortstrings * sort_1_svc(sortstrings *, struct svc_req *);
extern int sortprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SORT 1
extern  sortstrings * sort_1();
extern  sortstrings * sort_1_svc();
extern int sortprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str (XDR *, str*);
extern  bool_t xdr_sortstrings (XDR *, sortstrings*);

#else /* K&R C */
extern bool_t xdr_str ();
extern bool_t xdr_sortstrings ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SORT_H_RPCGEN */
