/* @(#)msg_proc.c	2.1 88/08/11 4.0 RPCSRC */
/* modified by Amit Jain */
/*
 * msg_server.c: implementation of the remote procedure "printmessage"
 */
#include <stdio.h>
#include <rpc/rpc.h>	/* always need this here */
#include "msg.h"	/* need this too: msg.h will be generated by rpcgen */

/*
 * Remote verson of "printmessage"
 */
int *printmessage_1_svc(char **msg, struct svc_req *req)
{
	static int result; /* must be static! */
	FILE *f;

	f = fopen("/dev/tty", "w");
	if (f == NULL) {
		result = 0;
		return (&result);
	}
	fprintf(f, "%s\n", *msg);
	fclose(f);
	result = 1;
	return (&result);
}
