# assumes rpcgen now accessed either the TI-RPC protocol compiler
# rpcgen or rpcgen.new (feature-filled successor).  One way to
# do this is override the RPCGEN symbol, 
# e.g. 'make RPCGEN=/home/cortex/projects/tirpcsrc/rpcgen.new/rpcgen.new'.

APPN = rtele
LFLAGS = -lrpc -ldl -lnsl
include ../../makefile.template
