/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _USERLOOKUP_H_RPCGEN
#define _USERLOOKUP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define NOTFOUND 0
#define FOUND 1

typedef char *username;

struct uname_retval {
	int found;
	username name;
};
typedef struct uname_retval uname_retval;

struct uid_retval {
	int found;
	int uid;
};
typedef struct uid_retval uid_retval;

#define ULKUP_PROG 555555556
#define ULKUP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define byname 1
extern  uid_retval * byname_1(username *, CLIENT *);
extern  uid_retval * byname_1_svc(username *, struct svc_req *);
#define bynum 2
extern  uname_retval * bynum_1(int *, CLIENT *);
extern  uname_retval * bynum_1_svc(int *, struct svc_req *);
extern int ulkup_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define byname 1
extern  uid_retval * byname_1();
extern  uid_retval * byname_1_svc();
#define bynum 2
extern  uname_retval * bynum_1();
extern  uname_retval * bynum_1_svc();
extern int ulkup_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_username (XDR *, username*);
extern  bool_t xdr_uname_retval (XDR *, uname_retval*);
extern  bool_t xdr_uid_retval (XDR *, uid_retval*);

#else /* K&R C */
extern bool_t xdr_username ();
extern bool_t xdr_uname_retval ();
extern bool_t xdr_uid_retval ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_USERLOOKUP_H_RPCGEN */
