all:

CollectTimes: CollectTimes.kt
	kotlinc CollectTimes.kt -include-runtime -d CollectTimes.jar

ListInterfaces: ListInterfaces.kt
	kotlinc ListInterfaces.kt -include-runtime -d ListInterfaces.jar

clean:
	rm *.jar
