This is a better implementation of the RPC based username and uid lookup
system.  Here we include a request status indicator to the return type
of each remote procedure so we can really find out if the lookup worked.

For looking up usernames (given a uid), the remote procedure returns
a struct that contains a flag indicating whether or not the lookup
succeeded (whether the uid exists on the server system), and the actual
username as an RPC string.

The byname procedure returns a similar structure, this one contains a
flag indicating found/notfound and the resulting UID (when the lookup 
was successful).

Files:

userlookup.x: the protocol definition file. 
userlookup_services.c: the code for the remote procedures.
userlookup_client.c: the client main().

The other files are generated by rpcgen (_svc.c, _clnt.c, _xdr.c & .h).

