
all:
	cd linkedlist; make
	cd msg; make
	#cd multithreaded-square; make
	cd sort; make
	cd square; make
	cd thread-safe-square; make
	cd userlookup; make

clean:
	cd linkedlist; make clean
	cd msg; make clean
	#cd multithreaded-square; make clean
	cd sort; make clean
	cd square; make clean
	cd thread-safe-square; make clean
	cd userlookup; make clean
