/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sort.h"

bool_t
xdr_str (XDR *xdrs, str *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXSTRINGLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sortstrings (XDR *xdrs, sortstrings *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->ss.ss_val, (u_int *) &objp->ss.ss_len, MAXSORTSIZE,
		sizeof (str), (xdrproc_t) xdr_str))
		 return FALSE;
	return TRUE;
}
