all: subfolders

subfolders:
	cd setup-examples/; make
	cd ex1-mcast-hello/; make
	cd ex2-mcast-time/; make
	cd ex3-mcast-group/; make


clean:
		cd setup-examples/; make clean
		cd ex1-mcast-hello/; make clean
		cd ex2-mcast-time/; make clean
		cd ex3-mcast-group/; make clean
