all: subfolders

subfolders:
	cd ex0-mcast-setup/; make
	cd ex1-mcast-hello/; make
	cd ex2-mcast-time/; make
	cd ex3-mcast-group/; make


clean:
	cd ex0-mcast-setup/; make clean
	cd ex1-mcast-hello/; make clean
	cd ex2-mcast-time/; make clean
	cd ex3-mcast-group/; make clean
