#include	"ourhdr.h"		
#include	"square.h"		/* generated by rpcgen */

int main(int argc, char **argv)
{
	CLIENT		*cl;
	square_in	in;
	square_out	*outp;
	int i;
	int numcalls;

	if (argc != 4)
		err_quit("usage: client <hostname> <integer-value> <#calls>");
	
	numcalls = atoi(argv[3]);

	cl = clnt_create(argv[1], SQUARE_PROG, SQUARE_VERS, "udp");
	if (cl == NULL) {
		/* Couldn't establish connection with server.
		 * Print error message and die.
		 */
		clnt_pcreateerror(argv[1]);
		exit(1);
	}
	

	in.arg1 = atol(argv[2]);
	for (i=0; i<numcalls; i++) {
		if ( (outp = squareproc_1(&in, cl)) == NULL)
			err_quit("%s", clnt_sperror(cl, argv[1]));
		if (i % 1000 == 0) printf("Call #%16d result = %ld\r",i, outp->res1);
	}
	printf("Call #%16d result = %ld\n",i, outp->res1);

	exit(0);
}
