
all: 
	cd sockets; make 
	cd rmi-rpc; make 
	cd security; make
	cd serialization; make 
	cd multicasting; make 
	cd threads; make 


clean:
	cd sockets; make clean
	cd rmi-rpc; make clean
	cd security; make clean
	cd serialization; make clean
	cd multicasting; make clean
	cd threads; make clean


