
all: 
	cd sockets; make 
	cd sockets-C; make 
	cd rmi; make 
	cd rpc; make 
	cd security; make
	cd serialization; make 
	cd multicasting; make 
	cd threads; make 
	cd naming; make
	cd misc; make

clean:
	cd sockets; make clean
	cd sockets-C; make clean
	cd rmi; make clean
	cd rpc; make clean
	cd security; make clean
	cd serialization; make clean
	cd multicasting; make clean
	cd threads; make clean
	cd naming; make clean
	cd misc; make clean
