
all:
	cd ex1-HelloServer/; make
	cd ex2-SquareServer/; make
	cd ex3-Client-Callback/; make
	cd ex4-Load-Remote-Class/; make
	cd ex5-Asynchronous-Server/; make
	cd ex6-Dynamic-Classloading/; make
	cd ex7-RMI-Thread-Safety/; make

clean:
	cd ex1-HelloServer/; make clean
	cd ex2-SquareServer/; make clean
	cd ex3-Client-Callback/; make clean
	cd ex4-Load-Remote-Class/; make clean
	cd ex5-Asynchronous-Server/; make clean
	cd ex6-Dynamic-Classloading/; make clean
	cd ex7-RMI-Thread-Safety/; make clean
