
all:
	cd encryption; make
	cd secure-hash; make
	cd password-input; make
	cd providers; make
	cd SSL-Sockets; make
	cd RMI-SSL-ex1; make
	cd RMI-SSL-ex2; make

clean:
	cd encryption; make clean
	cd secure-hash; make clean
	cd password-input; make clean
	cd providers; make clean
	cd SSL-Sockets; make clean
	cd RMI-SSL-ex1; make clean
	cd RMI-SSL-ex2; make clean
