/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */


struct rpcgen_table messageprog_1_table[] = {

	(char *(*)())0,
 	(xdrproc_t) xdr_void,			0,
 	(xdrproc_t) xdr_void,			0,

	(char *(*)())RPCGEN_ACTION(printmessage_1_svc),
	xdr_wrapstring,			sizeof ( char *),
	xdr_int,			sizeof ( int ),
};
int messageprog_1_nproc =
	sizeof(messageprog_1_table)/sizeof(messageprog_1_table[0]);

