/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ll.h"

bool_t
xdr_foo (XDR *xdrs, foo *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (foo), (xdrproc_t) xdr_foo))
		 return FALSE;
	return TRUE;
}
