/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "msg.h"

bool_t
xdr_args_in (XDR *xdrs, args_in *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->heights.heights_val, (u_int *) &objp->heights.heights_len, 12,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->widths.widths_val, (u_int *) &objp->widths.widths_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
