/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "userlookup.h"
#define NOTFOUND 0
#define FOUND 1

bool_t
xdr_username (XDR *xdrs, username *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 10))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_uname_retval (XDR *xdrs, uname_retval *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->found))
		 return FALSE;
	 if (!xdr_username (xdrs, &objp->name))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_uid_retval (XDR *xdrs, uid_retval *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->found))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->uid))
		 return FALSE;
	return TRUE;
}
