
all:
	cd ex1-HelloServer/; make
	cd ex2-SquareServer/; make
	cd ex3-Client-Callback/; make
	cd ex4-Asynchronous-Server/; make
	cd ex5-Load-Remote-Class/; make
	cd ex6-RMI-Thread-Safety/; make

clean:
	cd ex1-HelloServer/; make clean
	cd ex2-SquareServer/; make clean
	cd ex3-Client-Callback/; make clean
	cd ex4-Asynchronous-Server/; make clean
	cd ex5-Load-Remote-Class/; make clean
	cd ex6-RMI-Thread-Safety/; make clean
