/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "square.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
squareproc_2(square_in *argp, square_out *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, SQUAREPROC,
		(xdrproc_t) xdr_square_in, (caddr_t) argp,
		(xdrproc_t) xdr_square_out, (caddr_t) clnt_res,
		TIMEOUT));
}
